version: "3"
services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: speedy
      POSTGRES_PASSWORD: notsecure
      POSTGRES_DB: carapp_db
  carapp:
    build: .
    environment:
      DB_HOST: postgresdb
      DB_USER: speedy
      DB_PASSWORD: notsecure
      DB_NAME: carapp_db
    depends_on:
      - postgresdb
    ports:
      - "8080:8080"

volumes:
  carapp_volume: {}


